#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Format: 1.0
Type: Application
FullName: io.murano.apps.docker.kubernetes.KubernetesCluster
Name: Kubernetes Cluster
Description: |
 Kubernetes is an open source system for managing containerized applications across multiple hosts,
 providing basic mechanisms for deployment, maintenance, and scaling of applications.
Author: 'Mirantis, Inc'
Tags: [Docker, Kubernetes]
Classes:
 io.murano.apps.docker.kubernetes.KubernetesCluster: KubernetesCluster.yaml
 io.murano.apps.docker.kubernetes.KubernetesMasterNode: KubernetesMasterNode.yaml
 io.murano.apps.docker.kubernetes.KubernetesMinionNode: KubernetesMinionNode.yaml
 io.murano.apps.docker.kubernetes.KubernetesGatewayNode: KubernetesGatewayNode.yaml
 io.murano.apps.docker.kubernetes.KubernetesNode: KubernetesNode.yaml
Require:
  io.murano.apps.docker.Interfaces:
